---
- name: "Varnish Custom Statistics"
  hosts: "statistics"
  tasks:
    - name: "Install components"
      yum: name="{{ item }}" state="installed"
      with_items:
        - "varnish-custom-statistics"

    - name: "Ensure services are running"
      service: name="{{ item }}" state="running"
      with_items:
        - "vstatd"

  handlers:
    - name: "Restart vstatd"
      service: name="vstatd" state="restarted"

